#
# Travis-CI configuration for grunt-vuecc.
#
sudo: false
language: node_js
node_js:
    - "iojs"
    - "0.10"
    - 0.11

# Prerequisites:
# * Install grunt.
# * Install vue-component-compiler (vuecc-compiler package).
before_install: 
    - npm install -g grunt-cli
    - npm install grunt
    - npm install -g vuecc-compiler

# Invoke tests for grunt.
script: npm test
